version: '3.7'

services:
  mc:
    image: alpine-minio-client
    command: bash -c "startup.sh && crond -f -l 8 -L /proc/1/fd/1 2> /proc/1/fd/1" 
    environment:
      - MC_HOST_minio=http://minioadmin:minioadmin@minio:9000
    volumes:
      - ./cron/startup.sh:/usr/local/bin/startup.sh:ro
      - ./cron/scripts/1m:/etc/periodic/1m:ro

  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./s3:/data
      - ./config:/root/.minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DOMAIN=data.bibliometrics.lib.kth.se
      - MINIO_SERVER_URL=https://data.mydomain.org
      - MINIO_BROWSER_REDIRECT_URL=https://console.data.mydomain.org
    labels:
      - "traefik.enable=true"
      # Console
      - "traefik.http.routers.minio-console.rule=Host(`console.data.mydomain.org`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=alpn"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # APi
      - "traefik.http.routers.minio.rule=Host(`data.mydomain.org`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=alpn"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
